chromium: Add another GCC 5.4.0 workaround.
Chromium currently builds with -std=gnu++14, which causes problems when we
use GCC 5.4.0. The excerpt below is from a MACHINE="raspberrypi3" build:

In file included from ../../third_party/tcmalloc/chromium/src/malloc_hook_mmap_linux.h:51:0,
                 from ../../third_party/tcmalloc/chromium/src/malloc_hook.cc:698:
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h: In function 'int sys_clone(int (*)(void*), void*, int, void*, int*, void*, int*)':
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1446:23: error: address of explicit register variable '__res' requested
       LSS_RETURN(int, __res);
                       ^
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:755:27: note: in definition of macro 'LSS_RETURN'
       if ((unsigned long)(res) >= (unsigned long)(-4095)) {                   \
                           ^
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1446:23: error: address of explicit register variable '__res' requested
       LSS_RETURN(int, __res);
                       ^
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:756:23: note: in definition of macro 'LSS_RETURN'
         LSS_ERRNO = -(res);                                                   \
                       ^
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1446:23: error: address of explicit register variable '__res' requested
       LSS_RETURN(int, __res);
                       ^
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:759:22: note: in definition of macro 'LSS_RETURN'
       return (type) (res);                                                    \
                      ^

This looks like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67064, which
got fixed in GCC 6.1.0 and later. For now, just removing the parenthesis
from the affected lines does the trick.

Signed-off-by: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>